### ISSUE TITLE
attribution needed?

### ISSUE THREAD

**Issue by diatomsRcool** [ClearEarthProject/EOL_harvest#2]
What kind of attribution do we need to keep track of for this text?

**Comment by MarthaSPalmer** [comment]
sorry, I need a little more context.  what do you mean by "this text" and what are the attribution choices?

**Comment by diatomsRcool** [comment]
"this text" is the text data objects from EOL. EOL keeps several layers of attribution for each text data object and also generates a unique data object ID and URl for each. We can keep track of who provided the text to EOL and who provided the text to that provider.

**Comment by diatomsRcool** [comment]
or we can just use the EOL generated ID and allow anyone who cares to follow the link and look it up for themselves.

**Comment by KatjaSchulz** [comment]
It depends on how you want to use the text.  For internal purposes, you can just keep track of the EOL data object ID.  If you expose the text to the world, you would need to provide easy access to full attribution & licensing information.

**Comment by MarthaSPalmer** [comment]
Sorry, I think I missed something. So somebody has already annotated a bunch of text strings in documents with EOL text data objects?  What is EOL?

We are probably ok with just keeping the ID's.

**Comment by diatomsRcool** [comment]
EOL is Encyclopedia of Life eol.org. It can provide us with lots of bio text for annotating. The annotation isn't done yet, we need to get it into anafora for annotation.

**Comment by MarthaSPalmer** [comment]
Katja's answer sounds right to me.

**Comment by diatomsRcool** [comment]
OK. I can add code to harvest the attribution and licensing information.

**Comment by diatomsRcool** [comment]
The code has been added. If tweeking is needed, please start another issue.
